export const START_RECORDING = 'START_RECORDING';
export type START_RECORDING = typeof START_RECORDING;

export const STOP_RECORDING = 'STOP_RECORDING';
export type STOP_RECORDING = typeof STOP_RECORDING;

export const TRANSCRIPTION_READY = 'TRANSCRIPTION_READY';
export type TRANSCRIPTION_READY = typeof TRANSCRIPTION_READY;